
DROP TABLE ACCT_BALANCE;

COMMIT;

ALTER SESSION SET DEFAULT_GLOBAL_SECONDARY_INDEX_CREATION = 0;

CREATE TABLE ACCT_BALANCE (
    ACCT_BALANCE_ID        NUMBER(20) NOT NULL,
    BALANCE_TYPE_ID        NUMBER(9) NOT NULL,
    EFF_DATE               DATE,
    EXP_DATE               DATE,
    BALANCE                NUMBER(20) NOT NULL,
    CHARGE1                NUMBER(20) NOT NULL,
    CHARGE2                NUMBER(20) NOT NULL,
    CYCLE_UPPER            NUMBER(20) NOT NULL,
    CYCLE_LOWER            NUMBER(20) NOT NULL,
    CYCLE_UPPER_TYPE       VARCHAR2(3),
    CYCLE_LOWER_TYPE       VARCHAR2(3),
    "STATE"                VARCHAR2(3) NOT NULL,
    STATE_DATE             DATE,
    ACCT_ID                NUMBER(20) NOT NULL,
    SERV_ID                NUMBER(20) NOT NULL,
    ITEM_GROUP_ID          NUMBER(9) NOT NULL,
    OBJECT_TYPE_ID         NUMBER(9) NOT NULL,
    LOWER_BILLING_CYCLE_ID NUMBER(9) NOT NULL,
    UPPER_BILLING_CYCLE_ID NUMBER(9) NOT NULL,
    "PRIORITY"             NUMBER(9) NOT NULL,
    PRIMARY KEY (ACCT_BALANCE_ID) )
;
	

COMMIT;

CREATE INDEX IDX_ACCT_BALANCE_1 ON ACCT_BALANCE (ACCT_ID, "STATE");

COMMIT;

CREATE INDEX IDX_ACCT_BALANCE_TYPE ON ACCT_BALANCE (BALANCE_TYPE_ID);

COMMIT;

CREATE INDEX I_PRIORITY ON ACCT_BALANCE ("PRIORITY");

COMMIT;

