DROP VIEW IF EXISTS PERFORMANCE_VIEW_SCHEMA.TECH_SESSION_WAIT_EVENT;

CREATE VIEW PERFORMANCE_VIEW_SCHEMA.TECH_SESSION_WAIT_EVENT
(
  MEMBER_NAME,
  ID,
  SERIAL,
  PROGRAM,
  WAIT_ID,
  WAIT_NAME,
  WAIT_DESC,
  TOTAL_WAITS,
  TOTAL_TIMEOUT,
  TIME_WAITED,
  AVERAGE_WAIT,
  MAX_WAIT,
  --CLASS_ID,
  CLASS_NAME,
  CLASS_DESC
)
AS
SELECT
  NVL(XSE.CLUSTER_MEMBER_NAME, 'STANDALONE') MEMBER_NAME,
  XS.ID ID,
  XS.SERIAL SERIAL,
  XS.PROGRAM PROGRAM,
  XWEN.WAIT_EVENT_ID WAIT_ID,
  XWEN.NAME WAIT_NAME,
  XWEN.DESCRIPTION WAIT_DESC,
  XSE.TOTAL_WAITS TOTAL_WAITS,
  XSE.TOTAL_TIMEOUTS TOTAL_TIMEOUT,
  XSE.TIME_WAITED TIME_WAITED,
  XSE.AVERAGE_WAIT AVERAGE_WAIT,
  XSE.MAX_WAIT MAX_WAIT,
 -- XWECN.CLASS_ID CLASS_ID,
  XWECN.NAME CLASS_NAME,
  XWECN.DESCRIPTION CLASS_DESC
FROM
  X$SESSION_EVENT XSE,
  X$SESSION XS,
  X$WAIT_EVENT_CLASS_NAME XWECN,
  X$WAIT_EVENT_NAME XWEN
WHERE
  1 = 1 AND
  NVL(XSE.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XS.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(XSE.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XWECN.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(XSE.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XWEN.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(XS.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XWECN.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(XS.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XWEN.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(XWECN.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XWEN.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  XSE.SESSION_ID = XS.ID AND
  XSE.WAIT_EVENT_ID = XWEN.WAIT_EVENT_ID AND
  XWEN.CLASS_ID = XWECN.CLASS_ID AND
  XS.TOP_LAYER != 12 AND
  XS.PROGRAM != 'cluster peer'
ORDER BY MEMBER_NAME, ID, WAIT_ID;

GRANT SELECT ON TABLE PERFORMANCE_VIEW_SCHEMA.TECH_SESSION_WAIT_EVENT TO PUBLIC;