DROP VIEW IF EXISTS PERFORMANCE_VIEW_SCHEMA.TECH_USER;

CREATE VIEW PERFORMANCE_VIEW_SCHEMA.TECH_USER
(
  MEMBER_NAME,
  USER_NAME,
  LOCK_STATUS,
  TABLESPACE_TYPE,
  TABLESPACE_NAME
)
AS
SELECT
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') MEMBER_NAME,
  AU.AUTHORIZATION_NAME USER_NAME,
  US.LOCKED_STATUS LOCK_STATUS,
  TA.USAGE_TYPE TABLESPACE_TYPE,
  TA.TABLESPACE_NAME TABLESPACE_NAME
FROM
  AUTHORIZATIONS AU,
  USERS US,
  TABLESPACES TA
WHERE
  1 = 1 AND
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(US.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(TA.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(US.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(TA.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  AU.AUTH_ID = US.AUTH_ID AND
  US.DEFAULT_DATA_TABLESPACE_ID = TA.TABLESPACE_ID
UNION
SELECT
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') MEMBER_NAME,
  AU.AUTHORIZATION_NAME USER_NAME,
  US.LOCKED_STATUS LOCK_STATUS,
  TA.USAGE_TYPE TABLESPACE_TYPE,
  TA.TABLESPACE_NAME TABLESPACE_NAME
FROM
  AUTHORIZATIONS AU,
  USERS US,
  TABLESPACES TA
WHERE
  1 = 1 AND
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(US.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(TA.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(US.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(TA.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  AU.AUTH_ID = US.AUTH_ID AND
  US.DEFAULT_TEMP_TABLESPACE_ID = TA.TABLESPACE_ID 
ORDER BY 2, 3;

GRANT SELECT ON TABLE PERFORMANCE_VIEW_SCHEMA.TECH_USER TO PUBLIC;