DROP VIEW IF EXISTS PERFORMANCE_VIEW_SCHEMA.TECH_UNUSED_COL;

CREATE VIEW PERFORMANCE_VIEW_SCHEMA.TECH_UNUSED_COL
(
  USER_NAME,
  SCHEMA_NAME,
  TABLE_NAME,
  COLUMN_ID,
  IS_UNUSED
)
AS  
SELECT
  AU.AUTHORIZATION_NAME USER_NAME,
  SC.SCHEMA_NAME SCHEMA_NAME,
  WT.TABLE_NAME TABLE_NAME,
  WH.COLUMN_ID COLUMN_ID,
  WH.IS_UNUSED IS_UNUSED
FROM
  DICTIONARY_SCHEMA.WHOLE_COLUMNS WH,
  DICTIONARY_SCHEMA.WHOLE_TABLES WT,
  DEFINITION_SCHEMA.SCHEMATA SC,
  AUTHORIZATIONS AU
WHERE
  WH.IS_UNUSED = 'TRUE' AND
  WH.OWNER_ID = WT.OWNER_ID AND
  WH.SCHEMA_ID = WT.SCHEMA_ID AND
  WH.TABLE_ID = WT.TABLE_ID AND
  WH.OWNER_ID = AU.AUTH_ID AND
  WH.SCHEMA_ID = SC.SCHEMA_ID;
  
GRANT SELECT ON TABLE PERFORMANCE_VIEW_SCHEMA.TECH_UNUSED_COL TO PUBLIC;
