DROP VIEW IF EXISTS PERFORMANCE_VIEW_SCHEMA.TECH_STATEMENT;

CREATE VIEW PERFORMANCE_VIEW_SCHEMA.TECH_STATEMENT
(
  MEMBER_NAME,
  STAT_BEGIN_TIME,
  USER_NAME,
  USER_ID,
  USER_SERIAL,
  CHARSET,
  PROGRAM,
  USER_LOGIN_TIME,
  SQL_TEXT
)
AS
SELECT
  NVL(XST.CLUSTER_MEMBER_NAME, 'STANDALONE') MEMBER_NAME,
  XST.START_TIME STAT_BEGIN_TIME,
  AU.AUTHORIZATION_NAME USER_NAME,
  XSE.ID USER_ID,
  XSE.SERIAL USER_SERIAL,
  XSE.CLIENT_CHARSET CHARSET,
  XSE.PROGRAM PROGRAM,
  XSE.LOGON_TIME USER_LOGIN_TIME,
  XST.SQL_TEXT SQL_TEXT
FROM
  AUTHORIZATIONS AU,
  X$SESSION XSE,
  X$STATEMENT XST
WHERE
  1 = 1 AND
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XSE.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(AU.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XST.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(XSE.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XST.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  AU.AUTH_ID = XSE.USER_ID AND
  XSE.ID = XST.SESSION_ID AND
  XSE.PROGRAM != 'cluster peer'
ORDER BY 2
;

GRANT SELECT ON PERFORMANCE_VIEW_SCHEMA.TECH_STATEMENT TO PUBLIC;