DROP VIEW IF EXISTS PERFORMANCE_VIEW_SCHEMA.TECH_CLUSTER;

CREATE VIEW PERFORMANCE_VIEW_SCHEMA.TECH_CLUSTER
(
  G_ID,
  M_ID,
  M_POS,
  NAME,
  STATUS,
  G_COORD,
  D_COORD,
  GLOBAL_SCN,
  LOCAL_SCN,
  AGABLE_SCN,
  AGABLE_SCN_GAP,
  IP,
  PORT
)
AS
SELECT
  CM.GROUP_ID G_ID,
  CM.MEMBER_ID M_ID,
  CM.MEMBER_POSITION M_POS,
  CM.MEMBER_NAME NAME,
  XCM.PHYSICAL_CONNECTION STATUS,
  XCM.IS_GLOBAL_COORD G_COORD,
  XCM.IS_DOMAIN_COORD D_COORD,
  XAI.GLOBAL_SCN GLOBAL_SCN,
  XAI.LOCAL_SCN LOCAL_SCN,
  XAI.AGABLE_SCN AGABLE_SCN,
  XAI.AGABLE_SCN_GAP AGABLE_SCN_GAP,
  XCL.HOST IP,
  XCL.PORT PORT
FROM
  CLUSTER_MEMBER@LOCAL CM,
  X$CLUSTER_MEMBER@LOCAL XCM,
  X$CLUSTER_LOCATION@LOCAL XCL,
  X$AGABLE_INFO XAI
WHERE
  1 = 1 AND
  NVL(CM.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XCM.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(CM.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XCL.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  --NVL(CM.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XAI.CLUSTER_MEMBER_NAME, 'STANDALONE') AND
  NVL(XCM.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XCL.CLUSTER_MEMBER_NAME, 'STANDALONE') AND  
  --NVL(XCM.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XAI.CLUSTER_MEMBER_NAME, 'STANDALONE') AND  
  --NVL(XCL.CLUSTER_MEMBER_NAME, 'STANDALONE') = NVL(XAI.CLUSTER_MEMBER_NAME, 'STANDALONE') AND  
  CM.MEMBER_ID = XCM.MEMBER_ID AND
  CM.MEMBER_POSITION = XCM.MEMBER_POSITION AND
  CM.MEMBER_NAME = XCL.MEMBER_NAME AND
  CM.MEMBER_NAME = NVL(XAI.CLUSTER_MEMBER_NAME, 'STANDALONE')
ORDER BY 1, 2;

GRANT SELECT ON TABLE PERFORMANCE_VIEW_SCHEMA.TECH_CLUSTER TO PUBLIC;